# Generated by Django 5.0.4 on 2024-04-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.CharField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.everestkitchenpa.com%2Fassets%2Fpages%2Fseafood.html&psig=AOvVaw3JDLfibQJkihK_SaabWuYh&ust=1713957377190000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKCm7Paa2IUDFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
