# Generated by Django 5.0.4 on 2024-04-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.CharField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fdribbble.com%2Fshots%2F4187820-404-Food-Not-Found&psig=AOvVaw1k_0weNigEt-kXCOEt3npI&ust=1713957728847000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCIjh0aCc2IUDFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
